### ISSUE TITLE
edit line at front page

### ISSUE THREAD

**Issue by compie67** [xiaohutai/bolt-theme-html5up-twenty#1]
https://extensions.bolt.cm/view/2be07f72-56cf-11e4-866c-43d66b93a270

Great theme, love it but maybe i look over it where can i edit the lorum ipsum text
i have been looking everywhere ;-)

Thank you
Eric

**Comment by xiaohutai** [comment]
Hey Eric,

Sorry for the late reply. There's a `config.yml` in your theme folder, where you can override some of the hard-coded texts.

Sincerely,
Xiao
